// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdometerService.Models;

#nullable disable

namespace OdometerService.Migrations
{
    [DbContext(typeof(OdometerContext))]
    [Migration("20260525160501_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OdometerService.Models.Odometer", b =>
                {
                    b.Property<string>("ReadingId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Current_Kilometer")
                        .HasColumnType("int");

                    b.Property<string>("RegId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ReadingId");

                    b.ToTable("Odometers");
                });
#pragma warning restore 612, 618
        }
    }
}
