// <auto-generated />
using MasterService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterService.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20260526114128_Initial01")]
    partial class Initial01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MasterService.Models.Master", b =>
                {
                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FCRenewal")
                        .HasColumnType("int");

                    b.Property<int>("FreqDays")
                        .HasColumnType("int");

                    b.Property<int>("FreqKm")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceRenewal")
                        .HasColumnType("int");

                    b.Property<string>("NameOfService")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PermitRenewal")
                        .HasColumnType("int");

                    b.Property<int>("PollutionCertificateRenewal")
                        .HasColumnType("int");

                    b.HasKey("Type");

                    b.ToTable("Masters");
                });
#pragma warning restore 612, 618
        }
    }
}
